/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import AppPackage.AnimationClass;

/**
 *
 * @author mapac
 */
public class animationLoginWindow extends javax.swing.JFrame {

    animationLoginWindow a = this;

    /**
     * Creates new form animationLoginWindow
     */
    public animationLoginWindow() {
        new Thread()
        {
            int count;

            @Override
            public void run()
            {
                try
                {
                    Thread.sleep(5700);
                    a.setVisible(false);
                    new loginWindow().setVisible(true);
                }
                catch(InterruptedException e)
                {

                }
            }
        }.start();
        initComponents();     
        AnimationClass anim = new AnimationClass();
        anim.jLabelXLeft(mainFigure1.getX(), -1000, 5, 1, mainFigure1);
        anim.jLabelXRight(mainFigure2.getX(), 1000, 5, 1, mainFigure2);
        anim.jLabelYDown(mainFigure3.getY(), 1000, 5, 1, mainFigure3);
        anim.jLabelYDown(mainFigure4.getY(), 1000, 5, 1, mainFigure4);  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainFigure1 = new javax.swing.JLabel();
        mainFigure2 = new javax.swing.JLabel();
        mainFigure3 = new javax.swing.JLabel();
        mainFigure4 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainFigure1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainFigure1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainFigure1.png"))); // NOI18N
        jPanel1.add(mainFigure1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-23, -5, 590, 610));

        mainFigure2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainFigure2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainFigure2.png"))); // NOI18N
        jPanel1.add(mainFigure2, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, -5, 620, 610));

        mainFigure3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainFigure3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainFigure3.png"))); // NOI18N
        jPanel1.add(mainFigure3, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 152, 700, 450));

        mainFigure4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainFigure4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainFigure4.png"))); // NOI18N
        jPanel1.add(mainFigure4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 343, 580, 260));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoFade.gif"))); // NOI18N
        logo.setText("jLabel1");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mainFigure1;
    private javax.swing.JLabel mainFigure2;
    private javax.swing.JLabel mainFigure3;
    private javax.swing.JLabel mainFigure4;
    // End of variables declaration//GEN-END:variables
}
