/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author mapac
 */
public class cataloguesWindow extends javax.swing.JFrame {

    /**
     * Creates new form cataloguesWindow
     */
    public cataloguesWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pleventTitle = new javax.swing.JLabel();
        cataloguesInformation = new javax.swing.JLabel();
        countryButton = new javax.swing.JButton();
        provinceButton = new javax.swing.JButton();
        cantonButton = new javax.swing.JButton();
        districtButton = new javax.swing.JButton();
        categoriesButton = new javax.swing.JButton();
        countryLabel = new javax.swing.JLabel();
        provinceLabel = new javax.swing.JLabel();
        cantonLabel = new javax.swing.JLabel();
        districtLabel = new javax.swing.JLabel();
        categoriesLabel = new javax.swing.JLabel();
        closeWindow = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pleventTitle.setFont(new java.awt.Font("Edwardian Script ITC", 0, 72)); // NOI18N
        pleventTitle.setForeground(new java.awt.Color(8, 151, 157));
        pleventTitle.setText("Plevent");
        jPanel1.add(pleventTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 170, 60));

        cataloguesInformation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cataloguesInformation.setText("Información de catálogos");
        jPanel1.add(cataloguesInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        countryButton.setBackground(new java.awt.Color(255, 255, 255));
        countryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/country.png"))); // NOI18N
        countryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        countryButton.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(countryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        provinceButton.setBackground(new java.awt.Color(255, 255, 255));
        provinceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/province.png"))); // NOI18N
        provinceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(provinceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, 100));

        cantonButton.setBackground(new java.awt.Color(255, 255, 255));
        cantonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/canton.png"))); // NOI18N
        cantonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cantonButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 100, 100));

        districtButton.setBackground(new java.awt.Color(255, 255, 255));
        districtButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/district.png"))); // NOI18N
        districtButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(districtButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 300, 100, 100));

        categoriesButton.setBackground(new java.awt.Color(255, 255, 255));
        categoriesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/categories.png"))); // NOI18N
        categoriesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(categoriesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 300, 100, 100));

        countryLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        countryLabel.setText("País");
        jPanel1.add(countryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        provinceLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        provinceLabel.setText("Provincia");
        jPanel1.add(provinceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        cantonLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cantonLabel.setText("Cantón");
        jPanel1.add(cantonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 240, -1, -1));

        districtLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        districtLabel.setText("Distrito");
        jPanel1.add(districtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 410, -1, -1));

        categoriesLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        categoriesLabel.setText("Categorías");
        jPanel1.add(categoriesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 410, -1, -1));

        closeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeWindow.png"))); // NOI18N
        closeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowMouseClicked(evt);
            }
        });
        jPanel1.add(closeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseClicked
        this.setVisible(false);
        AdminWindow admin = new AdminWindow();
    }//GEN-LAST:event_closeWindowMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(cataloguesWindow.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cataloguesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cataloguesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cataloguesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cataloguesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cataloguesWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cantonButton;
    private javax.swing.JLabel cantonLabel;
    private javax.swing.JLabel cataloguesInformation;
    private javax.swing.JButton categoriesButton;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JLabel closeWindow;
    private javax.swing.JButton countryButton;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JButton districtButton;
    private javax.swing.JLabel districtLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel pleventTitle;
    private javax.swing.JButton provinceButton;
    private javax.swing.JLabel provinceLabel;
    // End of variables declaration//GEN-END:variables
}
