/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DBConnection.MySQLConnection;
import static DBConnection.MySQLConnection.deleteCountry;
import static DBConnection.MySQLConnection.insertNewCountry;
import static DBConnection.MySQLConnection.loadCountries;
import static DBConnection.MySQLConnection.updateCountry;
import Utils.Global;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mapac
 */
public class countryWindow extends javax.swing.JFrame {

    /**
     * Creates new form countryWindow
     */
    cataloguesWindow cataW;
    public countryWindow(cataloguesWindow cW) throws SQLException {
        Global.countriesInfo.clear();
        initComponents();
        fillCountriesComboBox();
        cataW = cW;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private void fillCountriesComboBox() throws SQLException
    {
        loadCountries();
        if (Global.getInfo_result == 1)
        {
            eliminateComboBox.removeAllItems();
            oldNameComboBox.removeAllItems();
            for (int countryNumber = 0; countryNumber < Global.countriesInfo.size(); countryNumber++)
            {
                eliminateComboBox.addItem(Global.countriesInfo.get(countryNumber).getName());
                oldNameComboBox.addItem(Global.countriesInfo.get(countryNumber).getName());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addTitle = new javax.swing.JLabel();
        addCountryLabel = new javax.swing.JLabel();
        eliminateTitle = new javax.swing.JLabel();
        eliminateLabel = new javax.swing.JLabel();
        modifyTitle = new javax.swing.JLabel();
        modifyCountryLabel = new javax.swing.JLabel();
        newNameLabel = new javax.swing.JLabel();
        addCountryField = new javax.swing.JTextField();
        eliminateComboBox = new javax.swing.JComboBox<>();
        oldNameComboBox = new javax.swing.JComboBox<>();
        newNameField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        eliminateButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        countryIcon = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(431, 426));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addTitle.setText("Agregar");
        jPanel1.add(addTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        addCountryLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addCountryLabel.setText("Agregar país");
        jPanel1.add(addCountryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        eliminateTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        eliminateTitle.setText("Eliminar");
        jPanel1.add(eliminateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        eliminateLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminateLabel.setText("Eliminar país");
        jPanel1.add(eliminateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, -1));

        modifyTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        modifyTitle.setText("Modificar");
        jPanel1.add(modifyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        modifyCountryLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modifyCountryLabel.setText("País a modificar");
        jPanel1.add(modifyCountryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, -1));

        newNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        newNameLabel.setText("Nuevo nombre");
        jPanel1.add(newNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 100, -1));

        addCountryField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(addCountryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 130, 21));

        eliminateComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eliminateComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(eliminateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 147, 130, 21));

        oldNameComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(oldNameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 257, 130, -1));

        newNameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(newNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 130, -1));

        addButton.setBackground(new java.awt.Color(8, 151, 157));
        addButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Agregar");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.setPreferredSize(new java.awt.Dimension(89, 25));
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        eliminateButton.setBackground(new java.awt.Color(8, 151, 157));
        eliminateButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminateButton.setForeground(new java.awt.Color(255, 255, 255));
        eliminateButton.setText("Eliminar");
        eliminateButton.setPreferredSize(new java.awt.Dimension(89, 25));
        eliminateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminateButtonMouseClicked(evt);
            }
        });
        jPanel1.add(eliminateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        modifyButton.setBackground(new java.awt.Color(8, 151, 157));
        modifyButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Modificar");
        modifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyButtonMouseClicked(evt);
            }
        });
        jPanel1.add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        countryIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/country.png"))); // NOI18N
        jPanel1.add(countryIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 110, 90));

        cancelButton.setBackground(new java.awt.Color(132, 116, 161));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        String newCountryName = addCountryField.getText();
        if (!"".equals(newCountryName) && !Global.isNumeric(newCountryName) && !Global.hasNumbers(newCountryName))
        {
            insertNewCountry(newCountryName);
            if (Global.insert_result == 1) JOptionPane.showMessageDialog(this,"Nuevo país ha sido agregado al catálogo","Modificación exitosa",JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this,"Error al insertar el país","Error de inserción",JOptionPane.ERROR_MESSAGE);
        }
        else JOptionPane.showMessageDialog(this,"Error al insertar el país","Error de inserción",JOptionPane.ERROR_MESSAGE);
        cataW.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addButtonMouseClicked

    private void eliminateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminateButtonMouseClicked
        int id_country = Global.countriesInfo.get(eliminateComboBox.getSelectedIndex()).getId();
        String name_country = Global.countriesInfo.get(eliminateComboBox.getSelectedIndex()).getName();
        deleteCountry(id_country,name_country);
        if (Global.delete_result == 1) JOptionPane.showMessageDialog(this,"El país ha sido eliminado","Borrado exitoso",JOptionPane.INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(this,"Error al eliminar el país","Error de borrado",JOptionPane.ERROR_MESSAGE);
        cataW.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminateButtonMouseClicked

    private void modifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyButtonMouseClicked
        int id_country = Global.countriesInfo.get(oldNameComboBox.getSelectedIndex()).getId();
        String old_name_country = Global.countriesInfo.get(oldNameComboBox.getSelectedIndex()).getName();
        String newCountryName = newNameField.getText();
        if (!"".equals(newCountryName) && !Global.isNumeric(newCountryName) && !Global.hasNumbers(newCountryName))
        {
            updateCountry(id_country,old_name_country,newCountryName);
            if (Global.update_result == 1) JOptionPane.showMessageDialog(this,"El nombre del país ha sido modificado","Modificación exitosa",JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this,"Error al modificar el país","Error de modificación",JOptionPane.ERROR_MESSAGE);
        }
        else JOptionPane.showMessageDialog(this,"Error al modificar el país","Error de modificación",JOptionPane.ERROR_MESSAGE);
        cataW.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        cataW.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addCountryField;
    private javax.swing.JLabel addCountryLabel;
    private javax.swing.JLabel addTitle;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel countryIcon;
    private javax.swing.JButton eliminateButton;
    private javax.swing.JComboBox<String> eliminateComboBox;
    private javax.swing.JLabel eliminateLabel;
    private javax.swing.JLabel eliminateTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel modifyCountryLabel;
    private javax.swing.JLabel modifyTitle;
    private javax.swing.JTextField newNameField;
    private javax.swing.JLabel newNameLabel;
    private javax.swing.JComboBox<String> oldNameComboBox;
    // End of variables declaration//GEN-END:variables
}
