/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static DBConnection.MySQLConnection.updateBirthDate;
import Utils.Global;
import javax.swing.JOptionPane;

/**
 *
 * @author mapac
 */
public class dateOfBirthWindow extends javax.swing.JFrame {

    /**
     * Creates new form dateOfBirthWindow
     */
    editProfile editP;
    public dateOfBirthWindow(editProfile ew) {
        initComponents();
        editP = ew;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateOfBithLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        iconDateOfBith = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 162));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateOfBithLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dateOfBithLabel.setText("Fecha de nacimiento");
        jPanel1.add(dateOfBithLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        dayLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dayLabel.setText("Día");
        jPanel1.add(dayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        monthLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        monthLabel.setText("Mes");
        jPanel1.add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 50, -1, -1));

        yearLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        yearLabel.setText("Año");
        jPanel1.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 50, -1, -1));

        iconDateOfBith.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDateOfBith.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dateOfBirth.png"))); // NOI18N
        jPanel1.add(iconDateOfBith, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, 80));

        dayComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(dayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 46, -1, -1));

        monthComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo ", "Abril ", "Mayo", "Junio", "Juilio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        monthComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(monthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 46, -1, -1));

        yearComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1993", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004" }));
        yearComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 46, -1, -1));

        cancelButton.setBackground(new java.awt.Color(132, 116, 161));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        acceptButton.setBackground(new java.awt.Color(8, 151, 157));
        acceptButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Aceptar");
        acceptButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptButton.setPreferredSize(new java.awt.Dimension(89, 25));
        acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButtonMouseClicked(evt);
            }
        });
        jPanel1.add(acceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboBoxActionPerformed

    private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButtonMouseClicked
        int monthNumber = monthComboBox.getSelectedIndex()+1;
        String month = String.valueOf(monthNumber);
        String day = dayComboBox.getSelectedItem().toString();
        String year = yearComboBox.getSelectedItem().toString();
        if(day.length() < 2) day = "0"+day;
        if (month.length() < 2) month = "0"+month;
        String format_date = year+"-"+month+"-"+day;
        String birth_date = dayComboBox.getSelectedItem().toString() +"/" +monthNumber+"/" + yearComboBox.getSelectedItem().toString();
        updateBirthDate(Global.person_id,birth_date,format_date);
        if (Global.update_result == 1) JOptionPane.showMessageDialog(this,"Fecha de nacimiento ha sido cambiada","Modificación exitosa",JOptionPane.INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(this,"La fecha de nacimiento no ha sido modificada","Error de modificación",JOptionPane.ERROR_MESSAGE);
        editP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_acceptButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        editP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dateOfBirthWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dateOfBirthWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dateOfBirthWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dateOfBirthWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel dateOfBithLabel;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JLabel iconDateOfBith;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
