/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static DBConnection.MySQLConnection.updateEmail;
import Utils.Global;
import javax.swing.JOptionPane;

/**
 *
 * @author lin
 */
public class emailWindow extends javax.swing.JFrame {
    editProfile ew;
    /**
     * Creates new form emailWindow
     */
    public emailWindow(editProfile ep) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        ew = ep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modifyTitle = new javax.swing.JLabel();
        oldEmailLabel = new javax.swing.JLabel();
        actualEmailLabel = new javax.swing.JLabel();
        oldEmailField = new javax.swing.JTextField();
        actualEmailField = new javax.swing.JTextField();
        iconPhone = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(460, 210));
        setSize(new java.awt.Dimension(460, 210));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        modifyTitle.setText("Modificar");
        jPanel1.add(modifyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        oldEmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        oldEmailLabel.setText("Correo electrónico anterior");
        jPanel1.add(oldEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, -1));

        actualEmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualEmailLabel.setText("Número de teléfono actual");
        jPanel1.add(actualEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, -1));

        oldEmailField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        oldEmailField.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(oldEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        actualEmailField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        actualEmailField.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel1.add(actualEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        iconPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.png"))); // NOI18N
        jPanel1.add(iconPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, 80));

        modifyButton.setBackground(new java.awt.Color(8, 151, 157));
        modifyButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Modificar");
        modifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyButtonMouseClicked(evt);
            }
        });
        jPanel1.add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        cancelButton.setBackground(new java.awt.Color(132, 116, 161));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyButtonMouseClicked
        String newMail = actualEmailField.getText();
        String oldMail = oldEmailField.getText();
        if (!newMail.equals(oldMail) && !"".equals(newMail) && !"".equals(oldMail))
        {
            updateEmail(oldMail,newMail,Global.person_id);
            if (Global.update_result == 1) JOptionPane.showMessageDialog(this,"Email modificado correctamente","Modificación exitosa",JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this,"No se ha podido modificar el email","Error en modificación",JOptionPane.ERROR_MESSAGE);
        }
        else JOptionPane.showMessageDialog(this,"No se ha podido modificar el email","Error en modificación",JOptionPane.ERROR_MESSAGE);
        ew.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        ew.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualEmailField;
    private javax.swing.JLabel actualEmailLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel iconPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel modifyTitle;
    private javax.swing.JTextField oldEmailField;
    private javax.swing.JLabel oldEmailLabel;
    // End of variables declaration//GEN-END:variables
}
