/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static DBConnection.MySQLConnection.updatePersonId;
import Utils.Global;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mapac
 */
public class idNumberWindow extends javax.swing.JFrame {

    /**
     * Creates new form idNumberWindow
     */
    editProfile editP;
    public idNumberWindow(editProfile ew) {
        initComponents();
        editP = ew;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idNUmberLabel = new javax.swing.JLabel();
        iconIdNumber = new javax.swing.JLabel();
        idNumberField = new javax.swing.JTextField();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(404, 149));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idNUmberLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        idNUmberLabel.setText("Cambiar número de cédula o pasaporte");
        jPanel1.add(idNUmberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, -1));

        iconIdNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconIdNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/idNumber.png"))); // NOI18N
        jPanel1.add(iconIdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 80, 70));

        idNumberField.setPreferredSize(new java.awt.Dimension(160, 23));
        jPanel1.add(idNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        acceptButton.setBackground(new java.awt.Color(8, 151, 157));
        acceptButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Aceptar");
        acceptButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptButton.setPreferredSize(new java.awt.Dimension(90, 25));
        acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButtonMouseClicked(evt);
            }
        });
        jPanel1.add(acceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        cancelButton.setBackground(new java.awt.Color(132, 116, 161));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setPreferredSize(new java.awt.Dimension(90, 25));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        editP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButtonMouseClicked
        if(Global.isNumeric(idNumberField.getText()) && !"".equals(idNumberField.getText())){
            int new_id = Integer.valueOf(idNumberField.getText());
            updatePersonId(Global.person_id,new_id);
            if (Global.update_result == 1) JOptionPane.showMessageDialog(this,"Cédula o pasaporte modificado con éxito","Modificación exitosa",JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this,"No es posible modificar la cédula o pasaporte.","Error de modificación.",JOptionPane.ERROR_MESSAGE);
        }
        else JOptionPane.showMessageDialog(this,"No es posible modificar la cédula o pasaporte.","Error de modificación.",JOptionPane.ERROR_MESSAGE);
        
        editP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_acceptButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel iconIdNumber;
    private javax.swing.JLabel idNUmberLabel;
    private javax.swing.JTextField idNumberField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
