/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.placeholder.PlaceHolder;

/**
 *
 * @author mapac
 */
public class loginWindow extends javax.swing.JFrame {

    /**
     * Creates new form loginWindow
     */
    public loginWindow() {
        initComponents();
        this.holders();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public void holders(){
        PlaceHolder holder;
        holder = new PlaceHolder(usernameField,"Usuario");
        holder = new PlaceHolder(passwordField,"Contraseña"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        pleventTitle = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        photoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(8, 151, 157));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Bienvenido");
        jPanel2.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 30));

        d1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        d1.setForeground(new java.awt.Color(255, 255, 255));
        d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d1.setText("Ingresa tus datos personales y empieza a  ");
        jPanel2.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 310, 30));

        d2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        d2.setForeground(new java.awt.Color(255, 255, 255));
        d2.setText("planear tus eventos con nosotros");
        jPanel2.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 120, 220, 20));

        registerButton.setBackground(new java.awt.Color(5, 91, 92));
        registerButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Registrarse");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.setMaximumSize(new java.awt.Dimension(121, 37));
        registerButton.setMinimumSize(new java.awt.Dimension(121, 37));
        registerButton.setPreferredSize(new java.awt.Dimension(130, 47));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        jPanel2.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, 40));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_pequeño.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, 370, 290));

        pleventTitle.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        pleventTitle.setForeground(new java.awt.Color(255, 255, 255));
        pleventTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pleventTitle.setText("Plevent");
        jPanel2.add(pleventTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 200, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 350, 600));

        loginLabel.setBackground(new java.awt.Color(0, 0, 0));
        loginLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        loginLabel.setText("Iniciar Sesión");
        loginLabel.setToolTipText("");
        jPanel1.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 50, 210, 50));

        usernameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 280, 40));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 280, 40));

        loginButton.setBackground(new java.awt.Color(5, 91, 92));
        loginButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Ingresar");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 130, 40));

        photoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user01.png"))); // NOI18N
        jPanel1.add(photoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 100, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        this.setVisible(false);
        registerWindow register = new registerWindow();
    }//GEN-LAST:event_registerButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel pleventTitle;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
