/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author mapac
 */
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
public class PendingEventsWindow extends javax.swing.JFrame {

    /**
     * Creates new form citizenWindow
     */
    queriesWindow quW;
    public PendingEventsWindow(queriesWindow qW) {
        initComponents();
        quW = qW;
        this.fillDateComboBox();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        closeWindow = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        communitiesTable = new javax.swing.JTable();
        startYearComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        startDayComboBox = new javax.swing.JComboBox<>();
        startMonthComboBox = new javax.swing.JComboBox<>();
        endDayComboBox = new javax.swing.JComboBox<>();
        endMonthComboBox = new javax.swing.JComboBox<>();
        endYearComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(579, 658));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(579, 645));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        closeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeWindow.png"))); // NOI18N
        closeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowMouseClicked(evt);
            }
        });
        jPanel1.add(closeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Eventos pendientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        communitiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(communitiesTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 200));

        startYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        startYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startYearComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(startYearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 70, -1));

        jLabel1.setText("Filtro fecha fin:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        jButton1.setBackground(new java.awt.Color(8, 151, 157));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel3.setText("Filtro fecha inicio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 20));

        startDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        startDayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDayComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(startDayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 60, -1));

        startMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        startMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMonthComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(startMonthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 60, -1));

        endDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        endDayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDayComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(endDayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 60, -1));

        endMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        endMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endMonthComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(endMonthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 60, -1));

        endYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        endYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endYearComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(endYearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(loginWindow.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseClicked
        quW.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_closeWindowMouseClicked

    private void startYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startYearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startYearComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.generatePendingEventsTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void startDayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDayComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDayComboBoxActionPerformed

    private void startMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMonthComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startMonthComboBoxActionPerformed

    private void endDayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDayComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDayComboBoxActionPerformed

    private void endMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endMonthComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endMonthComboBoxActionPerformed

    private void endYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endYearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endYearComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingEventsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingEventsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingEventsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingEventsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    private void fillDateComboBox()
    {
        startDayComboBox.removeAllItems();
        endDayComboBox.removeAllItems();
        startDayComboBox.addItem("Día");
        endDayComboBox.addItem("Día");
        
        startMonthComboBox.removeAllItems();
        endMonthComboBox.removeAllItems();
        startMonthComboBox.addItem("Mes");
        endMonthComboBox.addItem("Mes");
        
        startYearComboBox.removeAllItems();
        endYearComboBox.removeAllItems();
        startYearComboBox.addItem("Año");
        endYearComboBox.addItem("Año");
        for (int day = 1; day < 31; day++)
        {
            startDayComboBox.addItem(Integer.toString(day));
            endDayComboBox.addItem(Integer.toString(day));
        }
        
        for (int month = 1; month <= 12; month++)
        {
            startMonthComboBox.addItem(Integer.toString(month));
            endMonthComboBox.addItem(Integer.toString(month));
        }
        
        for (int year = 2000; year <= 2050; year++)
        {
            startYearComboBox.addItem(Integer.toString(year));
            endYearComboBox.addItem(Integer.toString(year));
        }
    }
    
    private void generateTable(ResultSet r) throws SQLException
    {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Evento"); 
        model.addColumn("Fecha de Inicio");
        model.addColumn("Fecha de Finalización");
        this.communitiesTable.setModel(model);
        while(r.next())
        {
            model.addRow(new Object[]{r.getString(1), r.getString(2), r.getString(3)});
        } 
    }
    
    private void generatePendingEventsTable()
    {
        try {
           Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           Logger.getLogger(PendingEventsWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        final String DB_URL =
            "jdbc:mysql://localhost:3306/eventsproject";
        final String DB_USER = "root";
        final String DB_PASSWD = "Mpca1606";
        try {
            ResultSet r = null;
            Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWD);
            CallableStatement stmt = con.prepareCall("{call getPendingEvents(?,?)}");
            if(startDayComboBox.getSelectedIndex() == 0 || startMonthComboBox.getSelectedIndex() == 0 || startYearComboBox.getSelectedIndex() == 0)
                stmt.setNull(1, Types.VARCHAR);
            else{
                String startDate = (String)startDayComboBox.getSelectedItem()+"/"+(String)startMonthComboBox.getSelectedItem()+"/"+(String)startYearComboBox.getSelectedItem();
                stmt.setString(1, startDate);
            }
            if(endDayComboBox.getSelectedIndex() == 0 || endMonthComboBox.getSelectedIndex() == 0 || endYearComboBox.getSelectedIndex() == 0)
                stmt.setNull(2, Types.VARCHAR);
            else{
                String endDate = (String)endDayComboBox.getSelectedItem()+"/"+(String)endMonthComboBox.getSelectedItem()+"/"+(String)endYearComboBox.getSelectedItem();
                stmt.setString(2, endDate);
            }
            r = stmt.executeQuery();
            generateTable(r);
        } catch (SQLException ex) {
            Logger.getLogger(PendingEventsWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeWindow;
    private javax.swing.JTable communitiesTable;
    private javax.swing.JComboBox<String> endDayComboBox;
    private javax.swing.JComboBox<String> endMonthComboBox;
    private javax.swing.JComboBox<String> endYearComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize;
    private javax.swing.JComboBox<String> startDayComboBox;
    private javax.swing.JComboBox<String> startMonthComboBox;
    private javax.swing.JComboBox<String> startYearComboBox;
    // End of variables declaration//GEN-END:variables
}
