/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static DBConnection.MySQLConnection.updatePersonPhoto;
import Utils.Global;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mapac
 */
public class photoWindow extends javax.swing.JFrame {

    /**
     * Creates new form photoWindow
     */
    editProfile editP;
    public photoWindow(editProfile ew) {
        initComponents();
        editP = ew;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPhoto = new javax.swing.JLabel();
        labelPreviewPhoto = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();
        selectPhoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPhoto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelPhoto.setText("Nueva foto de perfil");
        jPanel1.add(labelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, -1));

        labelPreviewPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 198, 202), 2));
        jPanel1.add(labelPreviewPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 128, 128));

        cancelButton.setBackground(new java.awt.Color(132, 116, 161));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        acceptButton.setBackground(new java.awt.Color(8, 151, 157));
        acceptButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Aceptar");
        acceptButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptButton.setMaximumSize(new java.awt.Dimension(89, 25));
        acceptButton.setMinimumSize(new java.awt.Dimension(89, 25));
        acceptButton.setPreferredSize(new java.awt.Dimension(89, 25));
        acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButtonMouseClicked(evt);
            }
        });
        jPanel1.add(acceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        selectPhoto.setBackground(new java.awt.Color(110, 198, 202));
        selectPhoto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectPhoto.setForeground(new java.awt.Color(255, 255, 255));
        selectPhoto.setText("Seleccionar");
        selectPhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectPhotoMouseClicked(evt);
            }
        });
        jPanel1.add(selectPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButtonMouseClicked
        String photo = "";
        if (Global.photoChooser.getSelectedFile() == null) 
            JOptionPane.showMessageDialog(this, "No es posible modificar la foto de perfil","Error de cambio", JOptionPane.ERROR_MESSAGE);
        else 
        {
            photo = Global.photoChooser.getSelectedFile().getName();
            updatePersonPhoto(Global.person_id,photo);
            if (Global.update_result == 1) JOptionPane.showMessageDialog(this, "La foto de perfil ha sido actualizada","Actualización exitosa", JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this, "No es posible modificar la foto de perfil","Error de cambio", JOptionPane.ERROR_MESSAGE);
        }
        Global.photoChooser.setSelectedFile(null);
        editP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_acceptButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        editP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void selectPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectPhotoMouseClicked
        Global.photoChooser.setDialogTitle("Seleccionar foto de perfil");
        Global.photoChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png"));
        if (Global.photoChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            labelPreviewPhoto.setIcon(new ImageIcon(Global.photoChooser.getSelectedFile().toString())); 
        }
    }//GEN-LAST:event_selectPhotoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JLabel labelPreviewPhoto;
    private javax.swing.JButton selectPhoto;
    // End of variables declaration//GEN-END:variables

}
