/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static DBConnection.MySQLConnection.updatePhone;
import Utils.Global;
import javax.swing.JOptionPane;

/**
 *
 * @author mapac
 */
public class telephoneWindow extends javax.swing.JFrame {

    /**
     * Creates new form telephoneWindow
     */
    editProfile editP;
    public telephoneWindow(editProfile ew) {
        initComponents();
        editP = ew;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        modifyTitle = new javax.swing.JLabel();
        oldPhoneLabel = new javax.swing.JLabel();
        actualPhoneLabel = new javax.swing.JLabel();
        actualPhoneField = new javax.swing.JTextField();
        oldPhoneField = new javax.swing.JTextField();
        iconPhone = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(456, 210));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        modifyTitle.setText("Modificar");
        jPanel2.add(modifyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        oldPhoneLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        oldPhoneLabel.setText("Número de teléfono anterior");
        jPanel2.add(oldPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, -1));

        actualPhoneLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualPhoneLabel.setText("Número de teléfono actual");
        jPanel2.add(actualPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, -1));

        actualPhoneField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        actualPhoneField.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel2.add(actualPhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        oldPhoneField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        oldPhoneField.setPreferredSize(new java.awt.Dimension(140, 21));
        jPanel2.add(oldPhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        iconPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phone.png"))); // NOI18N
        jPanel2.add(iconPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, 80));

        modifyButton.setBackground(new java.awt.Color(8, 151, 157));
        modifyButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Modificar");
        modifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyButtonMouseClicked(evt);
            }
        });
        jPanel2.add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        cancelButton.setBackground(new java.awt.Color(132, 116, 161));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setLabel("Cancelar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel2.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyButtonMouseClicked
        if (!actualPhoneField.getText().equals(oldPhoneField.getText()) && !"".equals(oldPhoneField.getText()) && Global.isNumeric(oldPhoneField.getText()) && !"".equals(actualPhoneField.getText()) && Global.isNumeric(actualPhoneField.getText()))
        {
            int oldPhone = Integer.valueOf(oldPhoneField.getText());
            int newPhone = Integer.valueOf(actualPhoneField.getText());
            updatePhone(oldPhone,newPhone,Global.person_id);
            if (Global.update_result == 1) JOptionPane.showMessageDialog(this,"Número telefónico modificado correctamente","Modificación exitosa",JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this,"Error al modificar el número telefónico","Error de modificación",JOptionPane.ERROR_MESSAGE);
        }
        else JOptionPane.showMessageDialog(this,"Error al modificar el número telefónico","Error de modificación",JOptionPane.ERROR_MESSAGE);
        editP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifyButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        editP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualPhoneField;
    private javax.swing.JLabel actualPhoneLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel iconPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel modifyTitle;
    private javax.swing.JTextField oldPhoneField;
    private javax.swing.JLabel oldPhoneLabel;
    // End of variables declaration//GEN-END:variables
}
