/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import AppPackage.AnimationClass;
import Utils.Global;
import javax.swing.JOptionPane;

/**
 *
 * @author lin
 */
public class UserWindow extends javax.swing.JFrame {

    /**
     * Creates new form UserWindow
     */
    public UserWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuIcon = new javax.swing.JLabel();
        minimizeWindIcon = new javax.swing.JLabel();
        closeWindIcon = new javax.swing.JLabel();
        myEventsIcon = new javax.swing.JLabel();
        createIcon = new javax.swing.JLabel();
        favoritesIcon = new javax.swing.JLabel();
        queriesIcon = new javax.swing.JLabel();
        accountSettingsIcon = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        menuIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIconMouseClicked(evt);
            }
        });
        jPanel1.add(menuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        minimizeWindIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeWindIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeWindIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeWindIconMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeWindIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, -1, -1));

        closeWindIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeWindow.png"))); // NOI18N
        closeWindIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeWindIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindIconMouseClicked(evt);
            }
        });
        jPanel1.add(closeWindIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, -1, -1));

        myEventsIcon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        myEventsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eventIcon.png"))); // NOI18N
        myEventsIcon.setText("Reseñas");
        myEventsIcon.setToolTipText("");
        myEventsIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myEventsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myEventsIconMouseClicked(evt);
            }
        });
        jPanel1.add(myEventsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-125, 60, -1, -1));

        createIcon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        createIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create.png"))); // NOI18N
        createIcon.setText("Crear evento");
        createIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createIconMouseClicked(evt);
            }
        });
        jPanel1.add(createIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-125, 102, -1, -1));

        favoritesIcon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        favoritesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.png"))); // NOI18N
        favoritesIcon.setText("Favoritos");
        favoritesIcon.setToolTipText("");
        favoritesIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        favoritesIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favoritesIconMouseClicked(evt);
            }
        });
        jPanel1.add(favoritesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-125, 144, -1, -1));

        queriesIcon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        queriesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/query.png"))); // NOI18N
        queriesIcon.setText("Consultas");
        queriesIcon.setToolTipText("");
        queriesIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        queriesIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queriesIconMouseClicked(evt);
            }
        });
        jPanel1.add(queriesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-125, 186, -1, -1));

        accountSettingsIcon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        accountSettingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userSettings.png"))); // NOI18N
        accountSettingsIcon.setText("Configuración");
        accountSettingsIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountSettingsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountSettingsIconMouseClicked(evt);
            }
        });
        jPanel1.add(accountSettingsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-125, 228, -1, -1));

        logoutIcon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logoutIcon.setText("Cerrar sesión");
        logoutIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutIconMouseClicked(evt);
            }
        });
        jPanel1.add(logoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-125, 270, -1, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 840, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindIconMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(this,"¿Seguro que desea salir?","Cerrar sesión",dialog);
        if (result == 0)
        {
            Global.login_result = -1;
            this.setVisible(false);
            loginWindow login = new loginWindow();
        }
    }//GEN-LAST:event_closeWindIconMouseClicked

    private void minimizeWindIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindIconMouseClicked
         this.setState(UserWindow.ICONIFIED);
    }//GEN-LAST:event_minimizeWindIconMouseClicked

    private void menuIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIconMouseClicked
        AnimationClass myEventsR = new AnimationClass();
        myEventsR.jLabelXRight(-125, 10, 10, 5, myEventsIcon);
        AnimationClass createR = new AnimationClass();
        createR.jLabelXRight(-125, 10, 10, 5, createIcon);
        AnimationClass favoritesR = new AnimationClass();
        favoritesR.jLabelXRight(-125, 10, 10, 5, favoritesIcon);
        AnimationClass queriesR = new AnimationClass();
        queriesR.jLabelXRight(-125, 10, 10, 5, queriesIcon);
        AnimationClass accSettingsR = new AnimationClass();
        accSettingsR.jLabelXRight(-125, 10, 10, 5, accountSettingsIcon);
        AnimationClass logoutR = new AnimationClass();
        logoutR.jLabelXRight(-125, 10, 10, 5, logoutIcon);
        //<--
        AnimationClass myEventsL = new AnimationClass();
        myEventsL.jLabelXLeft(10, -125, 10, 5, myEventsIcon);
        AnimationClass createL = new AnimationClass();
        createL.jLabelXLeft(10, -125, 10, 5, createIcon);
        AnimationClass favoritesL = new AnimationClass();
        favoritesL.jLabelXLeft(10, -125, 10, 5, favoritesIcon);
        AnimationClass queriesL = new AnimationClass();
        queriesL.jLabelXLeft(10, -125, 10, 5, queriesIcon);
        AnimationClass accSettingsL = new AnimationClass();
        accSettingsL.jLabelXLeft(10, -125, 10, 5, accountSettingsIcon);
        AnimationClass logoutL = new AnimationClass();
        logoutL.jLabelXLeft(10, -125, 10, 5, logoutIcon);
    }//GEN-LAST:event_menuIconMouseClicked

    private void accountSettingsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountSettingsIconMouseClicked
        this.setVisible(false);
        editProfile edit = new editProfile();
    }//GEN-LAST:event_accountSettingsIconMouseClicked

    private void createIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createIconMouseClicked
        this.setVisible(false);
        registerEvent event = new registerEvent(this);  
    }//GEN-LAST:event_createIconMouseClicked

    private void logoutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutIconMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(this,"¿Seguro que desea salir?","Cerrar sesión",dialog);
        if (result == 0)
        {
            Global.login_result = -1;
            this.setVisible(false);
            loginWindow login = new loginWindow();
        }
    }//GEN-LAST:event_logoutIconMouseClicked

    private void queriesIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queriesIconMouseClicked
        this.setVisible(false);
        queriesWindow queries = new queriesWindow();
    }//GEN-LAST:event_queriesIconMouseClicked

    private void favoritesIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoritesIconMouseClicked
        this.setVisible(false);
        favoritesWindow favorites = new favoritesWindow();
    }//GEN-LAST:event_favoritesIconMouseClicked

    private void myEventsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myEventsIconMouseClicked
        this.setVisible(false);
        reviewWindow reviewW = new reviewWindow();
    }//GEN-LAST:event_myEventsIconMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountSettingsIcon;
    private javax.swing.JLabel closeWindIcon;
    private javax.swing.JLabel createIcon;
    private javax.swing.JLabel favoritesIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JLabel minimizeWindIcon;
    private javax.swing.JLabel myEventsIcon;
    private javax.swing.JLabel queriesIcon;
    // End of variables declaration//GEN-END:variables
}
